# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-45ab21f8-2696-42ca-b35e-b29bb596e7d8";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-45ab21f8-2696-42ca-b35e-b29bb596e7d8".device =
    "/dev/disk/by-uuid/45ab21f8-2696-42ca-b35e-b29bb596e7d8";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-45ab21f8-2696-42ca-b35e-b29bb596e7d8";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-45ab21f8-2696-42ca-b35e-b29bb596e7d8";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E073-4353";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-3776db7c-a9d9-4afe-80cb-b10d0bf33035"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
